name: Deploy Fake
on:
    workflow_dispatch: 
      inputs:
        ambiente:
          type: string
          required: true
    repository_dispatch: 
      types:
        - deploy-remoto
jobs:
    deploy-kubernetes:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy no ambiente
              run: echo "Executando o deploy no ambiente de ${{ inputs.ambiente ||  github.event.client_payload.ambiente }}"

            - name: Curl Deploy no ambiente
              run: "curl -X POST https://webhook.site/4a711859-44a5-432e-97cf-f91ff0a7d579 -d '{ ambiente ${{ inputs.ambiente || github.event.client_payload.ambiente }}}'"